export const AGRIVISION_CONSTANTS = {
  DEFAULT_FARM_ID: 1,
  DEFAULT_FARM_NAME: 'Green Valley Farm',
  DEFAULT_LOCATION: 'Patna, Bihar',
  MAX_DRONE_ALTITUDE_METERS: 40.0,
  MIN_DRONE_ALTITUDE_METERS: 10.0,
  SAFE_WIND_SPEED_MAX_KMH: 18.0,
  OPTIMAL_DELTA_T_MIN: 2.0,
  OPTIMAL_DELTA_T_MAX: 8.0,
  PLATFORM_VERSION: 'v2.4.0-Hackathon-Edition'
} as const;
